### ISSUE TITLE
`other` should have a gradient in `__pow__` (?)

### ISSUE THREAD

**Issue by rokkosan** [karpathy/micrograd#17]
Hey Andrej -- just want to say thanks so much for your YouTube video on `micrograd`. The video has been absolutely enlightening.

Quick question -- while re-implementing `micrograd` on my end, I noticed that `__pow__` (in `Value`) was missing a back-propagation definition for `other`. Is this expected? https://github.com/karpathy/micrograd/blob/c911406e5ace8742e5841a7e0df113ecb5d54685/micrograd/engine.py#L39-L40

**Comment by karpathy** [comment]
hi, this is expected because the __pow__ we implemented assumes that other must be a scalar, see few lines above

```python
assert isinstance(other, (int, float)), "only supporting int/float powers for now"
```

**Comment by rokkosan** [comment]
Ah make sense, thanks!
