### ISSUE TITLE
Incorrect gradient when non-leaf Values are re-used

### ISSUE THREAD

**Issue by karpathy** [karpathy/micrograd#2]
Thank you @evcu for raising, my little 2D toy problem converged and instead of going on to proper tests and double checking through the recursion I got all trigger-happy and amused with puppies. The core issue is that if variables are re-used then their gradient will be accumulated for each path. Do you think this simpler reference counting idea will work as a potential simpler solution? The idea is to suppress `backward()` calls until the very last one.

(Love your Stylized puppy in your branch btw! :D) 

```python

class Value:
    """ stores a single scalar value and its gradient """

    def __init__(self, data):
        self.data = data
        self.grad = 0
        self.backward = lambda: None
        self.refs = 0

    def __add__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data + other.data)
        self.refs += 1
        other.refs += 1
        
        def backward():
            if out.refs > 1:
                out.refs -= 1
                return
            self.grad += out.grad
            other.grad += out.grad
            self.backward()
            other.backward()
        out.backward = backward

        return out

    def __radd__(self, other):
        return self.__add__(other)

    def __mul__(self, other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data * other.data)
        self.refs += 1
        other.refs += 1
        
        def backward():
            if out.refs > 1:
                out.refs -= 1
                return
            self.grad += other.data * out.grad
            other.grad += self.data * out.grad
            self.backward()
            other.backward()
        out.backward = backward

        return out

    def __rmul__(self, other):
        return self.__mul__(other)

    def relu(self):
        out = Value(0 if self.data < 0 else self.data)
        self.refs += 1
        def backward():
            if out.refs > 1:
                out.refs -= 1
                return
            self.grad += (out.data > 0) * out.grad
            self.backward()
        out.backward = backward
        return out

    def __repr__(self):
        return f"Value(data={self.data}, grad={self.grad})"
```

**Comment by karpathy** [comment]
Issue deprecated with https://github.com/karpathy/micrograd/commit/9fd9cc02fe5a0e57d790b03572f0d7bcd990662d

I was able to fix this and even make things much cleaner compared to where things started, imo. Closing.

**Comment by evcu** [comment]
Like the reference counting idea! But I think it wouldn't work when some outputs are stale and not connected to the loss. The Updated version looks nice!

**Comment by karpathy** [comment]
Yeah, it also wouldn't allow you to .backward() on arbitrary intermediate point in the calculation, etc. the topological sort ended up being quite clean and i combined it with a _backward vs backward distinction, which I think works nicely. Thanks again!!
