### ISSUE TITLE
Issue with zero_grad?

### ISSUE THREAD

**Issue by sky87** [karpathy/micrograd#25]
Hi, unless I'm misunderstanding something, `zero_grad` in `nn.py` is zeroing out the gradients on the parameter nodes, but shouldn't it do it on all the nodes in the graph?
Otherwise the inner nodes will keep accumulating them.

**Comment by sky87** [comment]
My bad, I didn't read the whole file carefully enough :)

**Comment by ben-z** [comment]
@sky87 what did you realize? I have the same question but haven't figured it out.

**Comment by ben-z** [comment]
From the looks of this: https://github.com/karpathy/micrograd/pull/8, this is still a known issue?

**Comment by sky87** [comment]
@ben-z It's been a few months, if I remember correctly the inner nodes are new Value instances that get recreated every time (see for example all the products and the sum in `Neuron#__call__`), so you don't need to zero them out. The parameters are the only thing that survives between runs

**Comment by ben-z** [comment]
> @ben-z It's been a few months, if I remember correctly the inner nodes are new Value instances that get recreated every time (see for example all the products and the sum in `Neuron#__call__`), so you don't need to zero them out. The parameters are the only thing that survives between runs

That makes a lot of sense!! Thanks for the explanation.
