### ISSUE TITLE
Zero_grad only zeros the weight and bias nodes, not the nodes for addition and multiplication

### ISSUE THREAD

**Issue by Tamulur** [karpathy/micrograd#32]
In zero_grad, we just zero the weight and bias graph nodes. But don't we need to zero the other graph nodes, like those created for addition and multiplication as well, since the backprop gradient flows through them as well?

**Comment by danielway** [comment]
The arithmetic nodes are recreated on each iteration during the forward pass, so we don't need to worry about their gradients carrying over into future iterations.
