### ISSUE TITLE
Would need 'substraction' support in Engine, mainly for regression loss functions like MSE

### ISSUE THREAD

**Issue by keyurfaldu** [karpathy/micrograd#4]

**Comment by karpathy** [comment]
Hahah alright that's fair. It seems like some people would want to use subtraction sometimes :)

**Comment by keyurfaldu** [comment]
On further thoughts, subtraction can always be derived with the help of addition and multiplication. So, you may want to keep Engine as lean as possible. 👍

**Comment by karpathy** [comment]
This is true, e.g. `a - b = a + (-1) * b`. But I still want to incorporate this. Thank you for raising! I'll reopen the issue because I plan to address it.

**Comment by karpathy** [comment]
Added the support for these with https://github.com/karpathy/micrograd/commit/315a2cb3e2cf04837c5133008e8afdedc9db5a04 . Closing the issue. Thank you!
