### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by aaditkapoor** [karpathy/micrograd#6]
## Feature
- Convert Micrograd into a PyPI package.

## Need
- Would be easier for institutions or bootcamps to help adopt this for their students.
- As an organizer of the Data Science Club at SJSU, I would love to introduce the fundamentals with this library.

**Comment by karpathy** [comment]
Granted, will work on.

**Comment by karpathy** [comment]
micrograd now exists on PyPI as of https://github.com/karpathy/micrograd/commit/c911406e5ace8742e5841a7e0df113ecb5d54685 .  Simply `pip install micrograd`. Thank you!
